# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QMessageBox, QInputDialog
from PyQt5.QtGui import QImage
from PyQt5.QtGui import QPixmap
from PIL import Image
import pytesseract
import cv2
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Nhận diện ký tự OCR - giangpt")
        MainWindow.resize(1063, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.picture = QtWidgets.QLabel(self.groupBox)
        self.picture.setText("")
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setObjectName("picture")
        self.horizontalLayout_3.addWidget(self.picture)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.result = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.result.setObjectName("result")
        self.horizontalLayout_2.addWidget(self.result)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 21))
        self.menubar.setObjectName("menubar")
        self.menuCh_n_file = QtWidgets.QMenu(self.menubar)
        self.menuCh_n_file.setObjectName("menuCh_n_file")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuCh_n_file.addSeparator()
        self.menuCh_n_file.addAction(self.actionOpen)
        self.menuCh_n_file.addSeparator()
        self.menuCh_n_file.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuCh_n_file.menuAction())

        self.actionOpen.triggered.connect(self.detect)
        self.actionExit_2.triggered.connect(MainWindow.close)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Hình ảnh"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kết quả"))
        self.menuCh_n_file.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))

    def detect(self):
        fname = QFileDialog.getOpenFileName(
            MainWindow, 'Open image file', os.getcwd(), "Image file (*.jpeg *.jpg *.png)")
        if fname[0] != "":
            # Đọc file ảnh bằng opencv
            img = cv2.imread(fname[0])
            # Hiển thị file ảnh
            height, width, channel = img.shape
            # Nếu ảnh có chiều rộng lớn hơn 640 pixel thì resize ảnh
            if width > 640:
                img = cv2.resize(img, (640, int((height * 640) / width)))
                height, width, channel = img.shape
            step = channel * width
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            QImg = QImage(img.data, width, height,
                          step, QImage.Format_RGB888)
            self.picture.setPixmap(QPixmap.fromImage(QImg))
            # Chuyển thành ảnh xám
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            # Phân tách đen trắng
            gray = cv2.threshold(
                gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
            # Ghi tạm ảnh xuống ổ cứng để sau đó apply OCR
            filename = "{}.png".format(os.getpid())
            cv2.imwrite(filename, gray)
            # Load ảnh và apply nhận dạng bằng Tesseract OCR
            text = pytesseract.image_to_string(
                Image.open(filename), lang='vie')
            # Xóa ảnh tạm sau khi nhận dạng
            os.remove(filename)
            # Hiển thị văn bản
            self.result.setPlainText(text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
